### ISSUE TITLE
Samples failing to build on MacOS and Windows

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn-samples-iec#28]
https://github.com/metanorma/mn-samples-iec/runs/1056711094?check_suite_focus=true , but applies for all but one samples repo with MacOS: metanorma executable not found

**Comment by opoudjis** [comment]
Update: current problem appears to be MacOS build failing to find yq, and Windows build failing to install chocolatey.

https://github.com/metanorma/mn-samples-iec/runs/1117803486?check_suite_focus=true
https://github.com/metanorma/mn-samples-iec/runs/1117803493?check_suite_focus=true

**Comment by CAMOBAP** [comment]
Fixed
